<html>
<head>
    <title>Wipfli LLP</title>
    <link rel="stylesheet" href="http://yui.yahooapis.com/pure/0.6.0/pure-min.css">
</head>
<body>
<h1 align="center">All Pets</h1>

<?php
if(count($pets) > 0):
?>
<table class="pure-table">
    <tr>
        <th>ID</th>
        <th>Name</th>
        <th>Breed</th>
        <th>Age</th>
        <th>Personality</th>
        <th>Phone</th>
        <th>City</th>
        <th>State</th>
        <th>Country</th>
        <th>Zip</th>
        <th></th>
    </tr>

<?php
    $odd = true;
    foreach($pets as $pet): 
?>
        <tr <?=$odd ? "class=\"pure-table-odd\"" : ""; ?>>
        <td><?=$pet->getId() ?></td>
        <td><?=$pet->getName() ?></td>
        <td><?=$pet->getBreed() ?></td>
        <td><?=$pet->getAge() ?></td>
        <td><?=$pet->getPersonality() ?></td>
        <td><?=$pet->getPersonality() ?></td>
        <td><?=$pet->getPersonality() ?></td>
        <td><?=$pet->getPersonality() ?></td>
        <td><?=$pet->getPersonality() ?></td>
        <td><?=$pet->getPersonality() ?></td>
        <td>
            <div id="view_pet" onclick="view('<? echo $pet->getId() ?>')">view</div>
        </td>
    </tr>
<?php 
    $odd = $odd ? false : true;
    endforeach; 
?>
</table>
<?php else: ?>
<p>No current tickets</p>
<?php endif; ?>

</body>
</html>

<script>
    var r = new XMLHttpRequest();
    r.open("POST", "path/to/api", true);
    r.onreadystatechange = function () {
        if (r.readyState != 4 || r.status != 200) return;
        alert("Success: " + r.responseText);
        };
    r.send("banana=yellow");
</script>